[package]
name = "sample"
version = "0.1.0"
authors = ["Shigenori Sagawa <shigenori.sagawa@net-marketing.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2 = "0.8.6"
r2d2_mysql = "17"
mysql = "17"